-- vim.cmd([[colorscheme catppuccin-mocha]])
-- vim.cmd[[colorscheme tokyonight-night]]
vim.cmd[[colorscheme tokyonight-night]]
-- vim.cmd([[highlight Normal guibg=none]])
vim.cmd([[highlight Normal guibg=none]])
vim.cmd([[highlight NormalNC guibg=none]])
vim.cmd([[highlight Comment guibg=none]])
vim.cmd([[highlight Constant guibg=none]])
vim.cmd([[highlight Special guibg=none]])
vim.cmd([[highlight Identifie guibg=none]])
-- vim.cmd([[highlight Statement guibg=none]])
vim.cmd([[highlight PreProc guibg=none]])
-- vim.cmd([[highlight Type guibg=none]])
-- vim.cmd([[highlight Underlined guibg=none]])
-- vim.cmd([[highlight Todo guibg=none]])
-- vim.cmd([[highlight String guibg=none]])
-- vim.cmd([[highlight Functio guibg=none]])
-- vim.cmd([[highlight Conditional guibg=none]])
-- vim.cmd([[highlight Repeat guibg=none]])
-- vim.cmd([[highlight Operator guibg=none]])
-- vim.cmd([[highlight Structure guibg=none]])
-- vim.cmd([[highlight LineNr guibg=none]])
-- vim.cmd([[highlight NonTex guibg=none]])
-- vim.cmd([[highlight SignColumn guibg=none]])
-- vim.cmd([[highlight CursorLine guibg=none]])
-- vim.cmd([[highlight CursorLineNr guibg=none]])
-- vim.cmd([[highlight StatusLine guibg=none]])
-- vim.cmd([[highlight StatusLineN guibg=none]])
-- vim.cmd([[highlight EndOfBuffe guibg=none]])
